name: Compiler and Deploy Repo

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de forcer manuellement le déploiement depuis l'onglet Actions

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dynamically Scan and Generate Indexes
      run: |
        echo "[*] Installing dpkg-dev and compression tools..."
        sudo apt-get update && sudo apt-get install -y dpkg-dev bzip2 gzip
        
        echo "[*] Scanning debs folder..."
        # On s'assure que le dossier debs existe
        mkdir -p debs
        
        # Génération du fichier Packages brut
        dpkg-scanpackages -m debs > Packages
        
        echo "[*] Compressing indexes..."
        rm -f Packages.gz Packages.bz2
        gzip -9fk Packages
        bzip2 -9fk Packages

    - name: Upload and Push Generated Files to Main Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Ajout forcé des index mis à jour
        git add -f Packages Packages.gz Packages.bz2
        
        # On ajoute le fichier Release s'il existe dans ton arborescence
        if [ -f "Release" ]; then git add -f Release; fi
        
        git commit -m "Autogen: Refresh repo indexes (.bz2, .gz) [skip ci]" || echo "No changes to commit"
        git push origin main

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

    - name: Finalize Status Notification
      run: |
        echo "========================================="
        echo " [V] Environment deployed successfully! "
        echo "========================================="
